export const CONFIG = {
  GOOGLE_EXCEL_KEY: process.env.NEXT_PUBLIC_GOOGLE_EXCEL_KEY || '',
  API_ENDPOINT: process.env.NEXT_PUBLIC_API_ENDPOINT || '',
  GOOGLE_SITE_KEY: process.env.NEXT_PUBLIC_GOOGLE_SITE_KEY || '',
};
